// <auto-generated />
using System;
using BluePoints_API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace BluePoints_API.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BluePoints_API.Models.Premio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Pontos")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("T_PREMIO");
                });

            modelBuilder.Entity("BluePoints_API.Models.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("Pontos")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("Id");

                    b.ToTable("T_USUARIO");
                });

            modelBuilder.Entity("BluePoints_API.Models.UsuarioPremio", b =>
                {
                    b.Property<int>("UsuarioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnOrder(0);

                    b.Property<int>("PremioId")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnOrder(1);

                    b.Property<DateTime>("DataResgate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.HasKey("UsuarioId", "PremioId");

                    b.HasIndex("PremioId");

                    b.ToTable("T_USUARIO_PREMIO");
                });

            modelBuilder.Entity("BluePoints_API.Models.UsuarioPremio", b =>
                {
                    b.HasOne("BluePoints_API.Models.Premio", "Premio")
                        .WithMany("UsuarioPremios")
                        .HasForeignKey("PremioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BluePoints_API.Models.Usuario", "Usuario")
                        .WithMany("UsuarioPremios")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Premio");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("BluePoints_API.Models.Premio", b =>
                {
                    b.Navigation("UsuarioPremios");
                });

            modelBuilder.Entity("BluePoints_API.Models.Usuario", b =>
                {
                    b.Navigation("UsuarioPremios");
                });
#pragma warning restore 612, 618
        }
    }
}
